Advantages
bonny-art/bonny-art-site pull request #56
Opened 2024-11-30 15:10 UTC by Aleksandr2905

2024-11-30 19:26 UTC, bonny-art requested changes

2024-11-30 19:26 UTC, bonny-art commented on messages/en.json
> +      "description": "After ordering, I will contact you promptly, and you will receive the desired diagrams very soon."
desired patterns

2024-11-30 19:26 UTC, bonny-art commented on messages/uk.json
> +  "AdvantagesSection": {
Заголовки на мобилке и десктопе сделай, пожалуйста, так, чтобі они біли поделені на 2 строчки как на скрине:
![image](https://github.com/user-attachments/assets/e2e1c292-661f-4d7a-be98-06f48d846708)
На таблете пусть в 1 строку будет

2024-11-30 19:26 UTC, bonny-art commented on messages/en.json
> +  "AdvantagesSection": {
В англ версии так же на мобилке и десктопе подели, пожалуста, на  строки, как на скрине:
![image](https://github.com/user-attachments/assets/38a0f62b-cf87-4905-a664-b4ac29af75b8)
На таблете пусть в 1 строку будет

2024-12-01 12:44 UTC, Aleksandr2905 commented on messages/en.json
> +      "description": "After ordering, I will contact you promptly, and you will receive the desired diagrams very soon."
+

2024-12-01 12:48 UTC, Aleksandr2905 commented on messages/uk.json
> +  "AdvantagesSection": {
десктоп там и есть по 2 строки, мобилку откорректировал

2024-12-01 13:08 UTC, Aleksandr2905 commented on messages/en.json
> +  "AdvantagesSection": {
если так
<img width="1083" alt="Снимок экрана 2024-12-01 в 15 08 11" src="https://github.com/user-attachments/assets/65fbea64-9d64-4c00-b13e-2101bcba806e">

2024-12-01 15:34 UTC, bonny-art requested changes

2024-12-01 15:34 UTC, bonny-art commented on messages/en.json
> +      "description": "After ordering, I will contact you promptly, and you will receive the desired patterns very soon."
давай це:
After ordering, I will contact you promptly, and you will receive the desired patterns very soon.
змінимо на :
After ordering, I will contact you, and you will receive the desired patterns very soon.

2024-12-01 16:39 UTC, bonny-art approved these changes

2024-12-01 16:39 UTC, merged